title: Thinking Out Loud
url: "https://jakecarter.github.io"
permalink: "post/:title/"

# pagination
paginate: 10
paginate_path: "page/:num/"

# custom
date_format: "%a, %b %d, %Y"

plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

theme: jekyll-theme-midnight