title: Thinking Out Loud
#url: "http://averagejake.com"
url: "https://jakecarter.github.io"
permalink: "post/:title/"

# pagination
paginate: 10
paginate_path: "page/:num/"

# custom
date_format: "%a, %b %d, %Y"
google_analytics: "UA-5806003-6"

plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
remote_theme: averagejake-jekyll-theme
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
